### ISSUE TITLE
install on Debian 11 - will this work

### ISSUE THREAD

**Issue by amravs** [Achronite/mqtt-energenie-ener314rt#27] opened 2023-02-22 11:25 UTC
Hi
install went well until I ran "node app.js"

pi@homeassistant:~/mqtt-energenie-ener314rt-master$ ^[[200~INFO: connecting to MQTT broker: mqtt://192.168.1.230:1883
energenie: child process started
ener314rt: can't open /dev/gpiomem or /dev/mem
energenie ERROR: failed to initialise ENER314-RT -6, EMULATION mode enabled
ERROR 'Error: Connection refused: Not authorized' connecting to MQTT broker: mqtt://192.168.1.230:1883

I'm assuming issue with the gpio? but don't know what. I have home assistant running on Debian 11 on a raspberry pi.

any help appreciated.

**Comment by Achronite** [comment] 2023-02-22 12:07
Try the solutions listed here: https://raspberrypi.stackexchange.com/questions/40105/access-gpio-pins-without-root-no-access-to-dev-mem-try-running-as-root

**Comment by amravs** [comment] 2023-02-22 15:22
tried your suggestion but the actual directory /dev/gpiomem doesn't exist. am i missing some gpio install?

**Comment by amravs** [comment] 2023-02-23 09:29
Thanks for the speedy responese - running as SUDO cleared the /dev/mem issue but now

pi@homeassistant:~/mqtt-energenie-ener314rt-master$ sudo node app.js
INFO: connecting to MQTT broker: mqtt://homeassistant
INFO: MQTT connected to broker mqtt://homeassistant
{"username":"node-ener314rt","password":"letmein","clean":true,"will":{"topic":"energenie/availability/state","payload":"offline","retain":true}}
INFO: setting energenie/availability/state to 'online'
INFO: MQTT discovery enabled at topic 'homeassistant/'
INFO: MQTT subscribed to energenie/+/+/+/command
energenie: child process started
ener314rt: mmap error -1
energenie ERROR: failed to initialise ENER314-RT -2, EMULATION mode enabled

assuming some issue with the board which is the ENER314-RT?

**Comment by Achronite** [comment] 2023-02-23 17:24
I don't think it will be the card (yet), the issue is it cannot initialise GPIO when it tries the map the memory.  What model of raspberry pi are you using? It *may* have a different peripheral memory base for GPIO.

Also can you tell me if this device exists `/proc/device-tree/soc/ranges` ?

**Comment by amravs** [comment] 2023-02-23 18:16
Hi

Raspberry 4, 64 bit, 8mb RAM

pi@homeassistant:~$ [[ -f /proc/device-tree/soc/ranges ]] && echo "This file exists!"
This file exists!
pi@homeassistant:~$


the debug software gives the following

pi@homeassistant:~/ener314rt-debug-master$ sudo node test.js
[sudo] password for pi:
napi_energenie.Init() called
test.js: Initialising board
init_ener314(): initialising
init_ener314(): mutex created & locked
radio_init
mmap error -1

**Comment by Achronite** [comment] 2023-02-23 18:38
And can you see the device? `/proc/device-tree/soc/ranges`

**Comment by amravs** [comment] 2023-02-23 18:43
Hi

pi@homeassistant:~$ ls -l /proc/device-tree/soc/ranges
-r--r--r-- 1 root root 48 Feb 23 08:57 /proc/device-tree/soc/ranges
pi@homeassistant:~$
I am not a unix expert

**Comment by amravs** [comment] 2023-02-23 18:43
pi@homeassistant:~$ ls -l /proc/device-tree/soc/ranges
-r--r--r-- 1 root root 48 Feb 23 08:57 /proc/device-tree/soc/ranges
pi@homeassistant:~$

**Comment by amravs** [comment] 2023-02-23 18:43
i don't know why lines are drawn through the text

**Comment by Achronite** [comment] 2023-02-23 19:11
lol - it's the two - signs if you put in \` \` it works.

Can you also paste the result of `cat /proc/iomem`

**Comment by amravs** [comment] 2023-02-23 19:23
'pi@homeassistant:~$ cat /proc/iomem
00000000-00000000 : System RAM
  00000000-00000000 : reserved
  00000000-00000000 : Kernel code
  00000000-00000000 : reserved
  00000000-00000000 : Kernel data
  00000000-00000000 : reserved
  00000000-00000000 : reserved
  00000000-00000000 : reserved
00000000-00000000 : System RAM
00000000-00000000 : fd500000.pcie pcie@7d500000
00000000-00000000 : fd580000.ethernet ethernet@7d580000
  00000000-00000000 : unimac-mdio.-19
00000000-00000000 : fe004000.txp txp@7e004000
00000000-00000000 : fe007000.dma dma@7e007000
00000000-00000000 : fe100000.watchdog watchdog@7e100000
00000000-00000000 : fe00b840.mailbox mailbox@7e00b840
00000000-00000000 : fe00b880.mailbox mailbox@7e00b880
00000000-00000000 : fe100000.watchdog watchdog@7e100000
00000000-00000000 : fe101000.cprman cprman@7e101000
00000000-00000000 : fe104000.rng rng@7e104000
00000000-00000000 : fe200000.gpio gpio@7e200000
00000000-00000000 : serial@7e201000
  00000000-00000000 : fe201000.serial serial@7e201000
00000000-00000000 : fe205000.i2c i2c@7e205000
00000000-00000000 : fe206000.pixelvalve pixelvalve@7e206000
00000000-00000000 : fe207000.pixelvalve pixelvalve@7e207000
00000000-00000000 : fe20a000.pixelvalve pixelvalve@7e20a000
00000000-00000000 : fe20c800.pwm pwm@7e20c800
00000000-00000000 : fe215000.aux aux@7e215000
00000000-00000000 : serial
00000000-00000000 : fe216000.pixelvalve pixelvalve@7e216000
00000000-00000000 : fe300000.mmc mmc@7e300000
00000000-00000000 : fe340000.mmc mmc@7e340000
00000000-00000000 : fe400000.hvs hvs@7e400000
00000000-00000000 : fe804000.i2c i2c@7e804000
00000000-00000000 : fe980000.usb usb@7e980000
00000000-00000000 : fef00000.clock clock@7ef00000
00000000-00000000 : fef04500.i2c auto-i2c
00000000-00000000 : fef04500.i2c bsc
00000000-00000000 : fef09500.i2c auto-i2c
00000000-00000000 : fef09500.i2c bsc
00000000-00000000 : System RAM
  00000000-00000000 : reserved
  00000000-00000000 : reserved
  00000000-00000000 : reserved
  00000000-00000000 : reserved
  00000000-00000000 : reserved
  00000000-00000000 : reserved
00000000-00000000 : pcie@7d500000
  00000000-00000000 : PCI Bus 0000:01
    00000000-00000000 : 0000:01:00.0
      00000000-00000000 : xhci-hcd
'

**Comment by Achronite** [comment] 2023-02-23 20:35
I've updated the debug edition https://github.com/Achronite/ener314rt-debug to add some extra diags, can you please run this and let me know the result?

**Comment by amravs** [comment] 2023-02-24 08:28
Hi

I don't get the output you have in your example
'
pi@homeassistant:~/ener314rt-debug-master$ sudo node test.js
napi_energenie.Init() called
test.js: Initialising board
init_ener314(): initialising
init_ener314(): mutex created & locked
radio_init
mmap error -1 (Operation not permitted) using gpio_base=2097152
'

**Comment by amravs** [comment] 2023-02-24 09:29
does this help
'pi@homeassistant:~$ pinout -r 9000c1
.-------------------------.
| oooooooooooooooooooo J8 |
| 1ooooooooooooooooooo   |c
---+       +---+ PiZero W|s
 sd|       |SoC|   V1.1  |i
---+|hdmi| +---+  usb pwr |
`---|    |--------| |-| |-'

Revision           : 9000c1
SoC                : BCM2835
RAM                : 512Mb
Storage            : MicroSD
USB ports          : 1 (excluding power)
Ethernet ports     : 0
Wi-fi              : True
Bluetooth          : True
Camera ports (CSI) : 1
Display ports (DSI): 0

J8:
   3V3  (1) (2)  5V
 GPIO2  (3) (4)  5V
 GPIO3  (5) (6)  GND
 GPIO4  (7) (8)  GPIO14
   GND  (9) (10) GPIO15
GPIO17 (11) (12) GPIO18
GPIO27 (13) (14) GND
GPIO22 (15) (16) GPIO23
   3V3 (17) (18) GPIO24
GPIO10 (19) (20) GND
 GPIO9 (21) (22) GPIO25
GPIO11 (23) (24) GPIO8
   GND (25) (26) GPIO7
 GPIO0 (27) (28) GPIO1
 GPIO5 (29) (30) GND
 GPIO6 (31) (32) GPIO12
GPIO13 (33) (34) GND
GPIO19 (35) (36) GPIO16
GPIO26 (37) (38) GPIO20
   GND (39) (40) GPIO21

'

**Comment by Achronite** [comment] 2023-02-24 09:40
The memory address for GPIO reported 2097152=0x200000 looks wrong; it should be 0x7e200000 (as reported by the /proc/imem). So I suspect that the read of /proc/device-tree/soc/ranges is failing for some reason, and it using the default (designed for raspberry pi 1)  instead.  This has the consequence that the memory mapping (mmap) to GPIO is failing.

I've uploaded a new version which should confirm this. Can you please download the debug code again?

Also, I see from your latest post is reporting a **Pi Zero W** as your device, is that correct?  I thought you said you were on a Pi4.

**Comment by amravs** [comment] 2023-02-24 09:56
Hi
it is definitely a pi 4


pi@homeassistant:~/ener314rt-debug-master$ sudo node test.js
napi_energenie.Init() called
test.js: Initialising board
init_ener314(): initialising
init_ener314(): mutex created & locked
radio_init
mmap error -1 (Operation not permitted) using gpio_base=0x00200000
pi@homeassistant:~/ener314rt-debug-master$

**Comment by amravs** [comment] 2023-02-24 09:57
try again 
'
pi@homeassistant:~/ener314rt-debug-master$ sudo node test.js
napi_energenie.Init() called
test.js: Initialising board
init_ener314(): initialising
init_ener314(): mutex created & locked
radio_init
mmap error -1 (Operation not permitted) using gpio_base=0x00200000
pi@homeassistant:~/ener314rt-debug-master$
'

**Comment by Achronite** [comment] 2023-02-24 10:05
> Hi it is definitely a pi 4

Mine does the same if using that command. Try just running `pinout` without any params.

**Comment by Achronite** [comment] 2023-02-24 10:11
I've been digging - are you using a 64bit OS on the Pi4?

**Comment by amravs** [comment] 2023-02-24 10:21
Hi
Yes 64 bit, if I run pin out without parameters it seems to error, unable to paste output at this time as internet is down, using my mobile

**Comment by Achronite** [comment] 2023-02-24 10:50
OK - I've uploaded a quick fix to the debug branch. Please try

**Comment by amravs** [comment] 2023-02-24 14:00
finally internet ia back

'
pi@homeassistant:~/ener314rt-debug-master$ sudo node test.js
napi_energenie.Init() called
test.js: Initialising board
init_ener314(): initialising
init_ener314(): mutex created & locked
radio_init
read of /proc/device-tree/soc/ranges returned 0, assuming 64 bit OS
radio_ver=255
warning:unexpected radio ver>exp
test.js: ERROR: Cannot initialise ENER314-RT board, status=255
test.js: Quitting
pi@homeassistant:~/ener314rt-debug-master$
'

**Comment by Achronite** [comment] 2023-02-24 14:07
damn, pasted the wrong value. pls try again :)

**Comment by amravs** [comment] 2023-02-24 14:34
'

pi@homeassistant:~/ener314rt-debug-master$ sudo node test.js
napi_energenie.Init() called
test.js: Initialising board
init_ener314(): initialising
init_ener314(): mutex created & locked
radio_init
read of /proc/device-tree/soc/ranges returned 0, assuming 64 bit OS
mmap error -1 (Operation not permitted) using gpio_base=0xfe200000
pi@homeassistant:~/ener314rt-debug-master$
'

**Comment by Achronite** [comment] 2023-02-24 15:39
I'm stumped now, 0xfe200000 seems to be the right address!

I'll have to done some more digging and get back to you.

Out of interest, have you enabled hardware spi mode as detailed in the instructions?  I *could* just disable the LEDs for now...

**Comment by amravs** [comment] 2023-02-24 15:50
I must have missed the hardware spi enablement, how do I do that?

**Comment by amravs** [comment] 2023-02-24 15:52
Just read the instructions, let me give it a go

**Comment by amravs** [comment] 2023-02-24 15:56
I don't have rapi-config on ,y machine as its a debian build for home assistant supervised

**Comment by amravs** [comment] 2023-02-24 16:43
tried to install raspi-config using this link and enabled spi
https://raspberrypi.stackexchange.com/questions/111728/how-to-get-raspi-config-on-ubuntu-20-04

'
pi@homeassistant:~/mqtt-energenie-ener314rt-master$ sudo node app.js
INFO: connecting to MQTT broker: mqtt://homeassistant
INFO: MQTT connected to broker mqtt://homeassistant
{"username":"node-ener314rt","password":"letmein","clean":true,"will":{"topic":"energenie/availability/state","payload":"offline","retain":true}}
INFO: setting energenie/availability/state to 'online'
INFO: MQTT discovery enabled at topic 'homeassistant/'
INFO: MQTT subscribed to energenie/+/+/+/command
energenie: child process started
ener314rt: mmap error -1
energenie ERROR: failed to initialise ENER314-RT -2, EMULATION mode enabled
> discovery
>energenie: cmd: { cmd: 'discovery', scan: false }
ener314rt: mmap error -1
ener314rt: mmap error -1
ener314rt: mmap error -1
ener314rt: mmap error -1
ener314rt: mmap error -1
ener314rt: mmap error -1
ener314rt: mmap error -1
ener314rt: mmap error -1

ener314rt: mmap error -1
ener314rt: mmap error -1
ener314rt: mmap error -1
INFO: discovery found 0 devices
'

running the debug

pi@homeassistant:~/ener314rt-debug-master$ sudo node test.js
napi_energenie.Init() called
test.js: Initialising board
init_ener314(): initialising
init_ener314(): mutex created & locked
radio_init
read of /proc/device-tree/soc/ranges returned 0, assuming 64 bit OS
mmap error -1 (Operation not permitted) using gpio_base=0xfe200000
'

**Comment by Achronite** [comment] 2023-02-25 07:44
Can you take a look at this thread pls? https://askubuntu.com/questions/1230947/gpio-for-raspberry-pi-gpio-group

**Comment by amravs** [comment] 2023-02-25 14:45
Hi

followed instructions
'
pi@homeassistant:~/ener314rt-debug-master$ sudo node test.js
[sudo] password for pi:
napi_energenie.Init() called
test.js: Initialising board
init_ener314(): initialising
init_ener314(): mutex created & locked
radio_init
read of /proc/device-tree/soc/ranges returned 0, assuming 64 bit OS
mmap error -1 (Operation not permitted) using gpio_base=0xfe200000
'

**Comment by amravs** [comment] 2023-02-25 14:51
If I don't use SUDO

'
pi@homeassistant:~$ cd ener314rt-debug-master
pi@homeassistant:~/ener314rt-debug-master$ ls
C  LICENSE  README.md  binding.gyp  build  test.js
pi@homeassistant:~/ener314rt-debug-master$ node test.js
napi_energenie.Init() called
test.js: Initialising board
init_ener314(): initialising
init_ener314(): mutex created & locked
radio_init
read of /proc/device-tree/soc/ranges returned 0, assuming 64 bit OS
can't open /dev/gpiomem or /dev/mem
'

**Comment by Achronite** [comment] 2023-02-26 07:48
We need to ensure that the environment you are working within can access GPIO pins.  Can you look at a few things for me?

1. What install type are you using for Home Assistant?
2. Are you running the command prompt within Home Assistant?  Is it native to debian or within Home Assistant, or a docker container, etc?
3. You said `pinout` didnt work the other day, what was the error that you couldn't paste at the time?
4. Can you try installing wiringPi and running `gpio` and paste the output? http://wiringpi.com/download-and-install/

**Comment by amravs** [comment] 2023-02-26 10:59
Hi

What install type are you using for Home Assistant? Home Assistant supervised on Debian 11 bullsout as per instructions
Are you running the command prompt within Home Assistant? Is it native to debian or within Home Assistant, or a docker container, etc?No, I use Putty to create an ssh session and enter all the commands
You said pinout didnt work the other day, what was the error that you couldn't paste at the time?
i have installed raspi-config but get the following error
'pi@homeassistant:~$ sudo raspi-config
/usr/bin/raspi-config: 947: dtparam: not found'
Can you try installing wiringPi and running gpio -v and paste the output? http://wiringpi.com/download-and-install/
this fails
'
pi@homeassistant:~/WiringPi$ gpio -v
gpio version: 2.70
Copyright (c) 2012-2018 Gordon Henderson
This is free software with ABSOLUTELY NO WARRANTY.
For details type: gpio -warranty

Oops: Unable to determine board revision from /proc/cpuinfo
 -> No "Hardware" line
 ->  You'd best google the error to find out why.
'
the SPI device isn't running as the correct devices haven't been set up in /dev eg /dev/gpiomem doesn't exist but /dev/mem does

**Comment by Achronite** [comment] 2023-02-26 13:57
I can only assume it is something to do with your install.  It seems there is little raspberry pi specific code, which unfortunately, is needed before my code can access the GPIO pins.

I'm no Linux expert either, so I'm really sorry but I can't help any further.  You need to get something working that proves GPIO is available for you (`pinout`, `gpio -v`, `pigpio`, anything really!).  We can then look at anything specifically to do with my code.

**Comment by amravs** [comment] 2023-02-26 14:07
Hi

I agree with you and considering going back to raspbian as I am interested in accessing my emergence switches through home assistant. Out of curiosity, before I switch, how easy is it to access the switches through home assistant ?

Regards
Sunny Varma
________________________________

**Comment by Achronite** [comment] 2023-02-26 15:27
When you say 'accessing my emergence switches through home assistant' do you mean energenie not 'emergence'?

If it is energenie ones, it depends on the model of the switch; the Control & Monitor ones (Smart Plug+) are easiest as it is auto-discovered via the monitor messages.  The standard switches can be added manually using mqtt config and 'taught' any zone/switch code - just follow the instructions once you get mqtt and node set-up.

**Comment by amravs** [comment] 2023-02-26 15:47
yes energenie :)

**Comment by Achronite** [comment] 2023-02-28 14:44
Closing as cannot be fixed by changes to code.

**Closed by Achronite** 2023-02-28 14:44 UTC
